/* 
 * File:   main.cpp
 * Author: Joshua Ludwig
 * Created on September 16, 2016, 8:45 AM
 * Purpose: Write a program that will predict how much the East Coast division 
 * will generate if the company has 8.6 million dollars in sales this year.
 */

//System Libraries Here
#include <iostream>
using namespace std;

//User Libraries Here

//Global Constants Only, No Global Variables
//Like PI, e, Gravity, or conversions

//Function Prototypes Here

//Program Execution Begins Here
int main(int argc, char** argv) {
    //Declare all Variables Here
    float Perc;     //percentage of the sales division
    int income,     //The 8.6 million of income this year
            total;  //The amount generated for the sales division team
    //Input or initialize values Here
    Perc = 0.58f;
    income = 8600000;
    total = Perc * income;

    //Process/Calculations Here
    cout<<"The total revenue generated by the sales team is $"<<total<<endl;
  
    //Output Located Here


    //Exit
    return 0;
}

